# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://github.com/anvaari/compair_iranian_stock_funds#%D8%A7%DB%8C%D9%86-%D9%BE%D8%B1%D9%88%DA%98%D9%87-%D8%A8%D8%B1%D8%A7%D9%85-%D9%85%D9%81%DB%8C%D8%AF-%D8%A8%D9%88%D8%AF%D9%87-%D9%88-%D9%85%DB%8C%D8%AE%D9%88%D8%A7%D9%85-%D8%AF%D9%88%D9%86%DB%8C%D8%AA-%DA%A9%D9%86%D9%85']
